%     semilogy(eval(join(['pt_Xi_',EE(iE),'_',CC(iC)],''))...
%             ,eval(join(['Bh_Xi_',EE(iE),'_',CC(iC)],''))/10^(iC-1),'k--','LineWidth',2.5)

%     eval(join(['h',iC,'=errorbar('...
%         ,'pt_Xi_',EE(iE),'_',CC(iC),','...
%         ,'dis_Xi_',EE(iE),'_',CC(iC),'/10^',num2str(iC-1),','...
%         ,'err_Xi_',EE(iE),'_',CC(iC),'/10^',num2str(iC-1),','...
%         ,list_errorbar_1(iC),');'],''))
%     eval(join(['set(h',num2str(iC),',''MarkerSize'',7,''MarkerFaceColor'','...
%         ,list_errorbar_2(iC),');'],''))